# Generated by Django 6.0.4 on 2026-05-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=32)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['trace_id', 'timestamp'], name='django_insp_trace_i_7702b5_idx')],
            },
        ),
    ]
