# Generated by Django 5.2.13 on 2026-09-30 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_inspector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', '-timestamp'], name='inspector_type_ts_idx'),
        ),
    ]
